root: true

extends:
  - "airbnb-typescript/base"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"

plugins:
  - "@typescript-eslint"
  - "@nrwl/nx"
  - "simple-import-sort"
  - "import"

parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  project: ./tsconfig.base.json

settings:
  import/resolver:
    typescript:

rules:
  sort-imports: "off"
  import/order: "off"
  simple-import-sort/imports: "error"
  simple-import-sort/exports: "error"

  "@nrwl/nx/enforce-module-boundaries":
    - error
    - enforceBuildableLibDependency: true
      allow: []
      depConstraints:
        - sourceTag: "*"
          onlyDependOnLibsWithTags:
            - "*"

  "@typescript-eslint/no-unused-vars":
    - error
    - vars: all
      args: after-used
      ignoreRestSiblings: true
      argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
